name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['1.17', '1.18', '1.19', '1.20', '1.21', '1.22', '1.23']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version:  ${{ matrix.go-version }}

    - name: Run tests on Windows after setting HOME environment variable
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        $env:HOME = $env:HOMEPATH
        echo "$HOME"
        go mod download github.com/stretchr/testify
        go test -v ./...

    - name: Run tests on POSIX
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        go mod download github.com/stretchr/testify
        go test -v ./...
